### PR TITLE
Fixed Laser Clustering

### PR DESCRIPTION
**Pull request by bkimelman**
Fixed issue with laser clustering being in two different macros. Removed it from Trkr_Clustering.C and updated version in Trkr_LaserClustering.C for use

### CODE REVIEW

**Comment by osbornjd** [comment]
Does anyone else use these other laser clustering modules (i.e. do we want to just remove them entirely)?

**Comment by bkimelman** [comment]
> Does anyone else use these other laser clustering modules (i.e. do we want to just remove them entirely)?

I don't think so. I'll check with Charles

**Comment by bkimelman** [comment]
> > Does anyone else use these other laser clustering modules (i.e. do we want to just remove them entirely)?
> 
> I don't think so. I'll check with Charles

Charles said it's fine to remove. It also makes sense as this is just for clustering. The analysis of the laser should be in a different macro that doesn't have to load the clustering libraries, which we can manage later

**Comment by osbornjd** [comment]
This macro change needs https://github.com/sPHENIX-Collaboration/coresoftware/pull/3089 to go through first

**Pull request merged**
