### PR TITLE
production macros with tpc reco init

### PR DESCRIPTION
**Pull request by bogui56**

### CODE REVIEW

**Comment by pinkenburg** [comment]
This PR needs more discussion. Passing the run number as an argument is really not what we want. This will break too many things downstream (also the production)

**Comment by osbornjd** [comment]
I was under the impression that the production scripts ran the macros from [here](https://github.com/klendathu2k/slurp-examples/tree/main/sPHENIX)? All of the streaming/tracking macros here take the run number as an argument

**Comment by bogui56** [comment]
I submitted the macro changes here so we can first of all run it through jenkins and then review/discuss how to properly move the changes to the production area.
Please have a look and advise...

**Comment by pinkenburg** [comment]
Resolved merging conflict by hand and merged this PR

**Pull request closed without merging**
