### PR TITLE
Josephb

### PR DESCRIPTION
**Pull request by josephbertaux**
Edited the coresofware repo so the correct things are """loaded by default"""

but left a comment about how to manually use/configure INTT calibrations

### CODE REVIEW

**Comment by josephbertaux** [comment]
Chris manually initiated a build that ties this to the coresoftware PR that I wanted to do--I'll see if that puts any output here and wait to hear from Chris or Jenkins

**Comment by josephbertaux** [comment]
Jenkins just finished, but it fails similarly. When I check the output, Trkr_Clustering fails the same way as before, even though this PR should remove the line where it fails.

Maybe I'm looking at older output and it's something new tripping it up, or what was tried earlier didn't use the newer version here.

I can try to trigger the build from the Jenkins prompt here, but Joe mentioned doing it a certain way on the PR I closed. If the offer still stands, Joe could you try to (re)build it? The coresoftware PR# is 2608

**Comment by osbornjd** [comment]
I just started another build to run over night just in case

**Comment by josephbertaux** [comment]
Thank you
________________________________

**Comment by osbornjd** [comment]
Build failed due to the unpacking job crashing:
https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-default-TrackingProduction-TrkrHitSet_Unpacker/630/artifact/macros/TrackingProduction/Fun4All_TrkrHitSet_Unpacker.C.log/*view*/

**Comment by osbornjd** [comment]
Somehow your commit history shows all the already merged commits. Once you are ready to test this with the coresoftware PR just ping me and I'll setup the build

**Comment by josephbertaux** [comment]
Edits were made to some of the macros that my PR affects while I was working on it, so I pulled the changes from my local master (I was expecting a conflict—fortunately there was none), and merged that to my feature branch. I think that's what caused it.

I can try closing this PR and open another one relative to my local master branch—the commit history looks a bit more reasonable there.
________________________________

**Comment by osbornjd** [comment]
I would suggest making a new PR as I don't think previously pushed commits should show up as new commits in your PR, somehow the branch history got messed up

**Comment by josephbertaux** [comment]
I agree, I'll close this one and open another.

**Pull request closed without merging**
