### PR TITLE
Fix truth reconstruction chain

### PR DESCRIPTION
**Pull request by hupereir**
set magnetic field parameter to relevant modules, to prevent exception when reading

### CODE REVIEW

**Comment by hupereir** [comment]
Side note: 
@jdosbo 
@adfrawley 
I also turned ON actsFit->set_use_clustermover(true), because I need it (right ?) to properly handle distortion corrections.
Is that the right thing to do ? And if yes, should I also commit the same change to Trkr_Reco.C ? 

Hugo

**Comment by adfrawley** [comment]
That is the default, so the macro should not need it.

I am in the process of trying to update the macros to properly run pp pileup events with distortions.

Tony
________________________________

**Comment by hupereir** [comment]
> That is the default, so the macro should not need it. I am in the process of trying to update the macros to properly run pp pileup events with distortions. Tony

in offline/packages/trackreco/PHActsTrkFitter.h, line 226: bool m_use_clustermover = false;

false is not the default (hence changing the flag in the macro. 
Should I change the default in the header to true ?

**Comment by sPHENIX-GitHub-l** [comment]
Hah! Yes, please do. That was a mistake - I must have changed it for testing and forgot to set it back. My macro had it set to true, so I did not notice.
The other option does not work yet.

Thanks
Tony
________________________________

**Pull request merged**
