### PR TITLE
Change BBC names to MBD names

### PR DESCRIPTION
**Pull request by mchiu-bnl**

### CODE REVIEW

**Comment by mchiu-bnl** [comment]
Needs to be coordinated with PR #2300:

https://github.com/sPHENIX-Collaboration/coresoftware/pull/2300

**Comment by osbornjd** [comment]
I just started a Jenkins pipeline that uses both PRs, here's the link:
https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/Build-Master-gcc12/1741/

**Comment by osbornjd** [comment]
Looks like it is still failing for a missing module (probably renamed)
https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-default-detector-pipeline/6638/artifact/macros/detectors/sPHENIX/Fun4All_G4_sPHENIX.log/*view*/

**Comment by mchiu-bnl** [comment]
Hi,

Yes, and that won’t be changed in the sims - it would be too disruptive.  The problem came from doing a global replace, so it changed too many things.  I will test the macro directly, and commit it when done.

Cheers,
Mickey

**Comment by osbornjd** [comment]
Let me know when this is ready to test again and I'll start another build

**Comment by mchiu-bnl** [comment]
OK, let's try again.

Thanks,
Mickey

**Comment by osbornjd** [comment]
Okay, here it is
https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/Build-Master-gcc12/1746/

**Comment by mchiu-bnl** [comment]
Hi,
I checked the logs, and I don’t think this failure has anything to do with the MBD/BBC code?
> Processing Fun4All_G4_sPHENIX.C(2)...
> PHRandomSeed::GetSeed() seed: 1770679725
> G4_TrkrSimulation::TpcInit
> ...
> Error in <TFile::Open>: no url specified
> could not open  for domain EMCTOWERCALIB
> Command exited with non-zero status 1


Cheers,
Mickey

**Comment by osbornjd** [comment]
@pinkenburg Mickey is right that the valgrind job only failed because of something with the EMC tower calibration file - is this a known issue and if so should we just go ahead and merge this and https://github.com/sPHENIX-Collaboration/coresoftware/pull/2300?

**Comment by pinkenburg** [comment]
I would rather run this again. The macro died at startup - so we don't know if the mbd actually works with the modified macros, which is the whole point of this test

**Pull request merged**
